
services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "sh web.entrypoint.sh"
    env_file:
      - ../example.env
    volumes:
      - ../src/:/src
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge