
services:
  main_app:
    container_name: main_app
    build:
        context: ..
        dockerfile: Dockerfile
    volumes:
      - ../src/:/fastoser/src/
    ports: 
        - "8000:8000"
    command: "sh /fastoser/entrypoint.sh" 
    depends_on:
      - postgres
    networks:
      - backend

networks: 
  backend:
    driver: bridge
