
services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "${DATABASE__PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
      - POSTGRES_DB=${DATABASE__NAME}    
    env_file:
      - ../example.env
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
